version: "3.3"
services:

  libface-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/opt/libface
    entrypoint: [ "/bin/bash" ]

  libface-dev-gpu:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev.gpu
    volumes:
      - ./:/opt/libface
    shm_size: 8gb
    runtime: nvidia
    entrypoint: [ "/bin/bash" ]

  libface-tests:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.tests
    volumes:
      - ./:/opt/libface
    entrypoint:
      [
        "conda",
        "run",
        "--no-capture-output",
        "-n",
        "env",
        "pytest",
        "-v",
        "--cov=libface",
        "--cov-report=term",
        "--cov-fail-under=95"
      ]

  libface-dev-example:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/opt/libface
    entrypoint:
      [
        "conda",
        "run",
        "--no-capture-output",
        "-n",
        "env",
        "python",
        "scripts/example.py"
      ]

  libface-lock:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.lock
    volumes:
      - ./:/opt/libface
    entrypoint:
      [
        "conda",
        "run",
        "--no-capture-output",
        "-n",
        "base",
        "conda-lock",
        "-p",
        "linux-64",
        "-f",
        "environment.yml",
        "--lockfile",
        "new.conda-lock.yml"
      ]

  libface-lock-gpu:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.lock
    volumes:
      - ./:/opt/libface
    runtime: nvidia
    entrypoint:
      [
        "conda",
        "run",
        "--no-capture-output",
        "-n",
        "base",
        "conda-lock",
        "-p",
        "linux-64",
        "-f",
        "gpu.environment.yml",
        "--lockfile",
        "new.gpu.conda-lock.yml"
      ]
