version: "3.3"
services:

  libface:
    image: liyibing666/libface:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/opt/libface
    entrypoint: [ "/bin/bash" ]

  libface-gpu:
    image: liyibing666/libface-gpu:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    volumes:
      - ./:/opt/libface
    runtime: nvidia
    entrypoint: [ "/bin/bash" ]

  libface-gpu-no-device:
    image: liyibing666/libface-gpu:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    volumes:
      - ./:/opt/libface
    entrypoint: [ "/bin/bash" ]
