name: docker-push

on:
  push:
    branches: [ "main" ]

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose build libface
        run: docker compose build libface
      - name: Login to Docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      - name: Docker compose push libface
        run: docker compose push libface
  docker-push-gpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose build libface-gpu
        run: docker compose build libface-gpu-no-device
      - name: Login to Docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      - name: Docker compose push libface-gpu
        run: docker compose push libface-gpu-no-device