name: docker-push

on:
  push:
    branches: [ "main" ]

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose build facetorch
        run: docker compose build facetorch
      - name: Login to Docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      - name: Docker compose push facetorch
        run: docker compose push facetorch
  docker-push-gpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose build facetorch-gpu
        run: docker compose build facetorch-gpu-no-device
      - name: Login to Docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      - name: Docker compose push facetorch-gpu
        run: docker compose push facetorch-gpu-no-device